# Generated by Django 5.0.7 on 2024-07-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='report_time',
            new_name='reportTime',
        ),
    ]
