# Generated by Django 5.0.7 on 2024-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_humidityinfo_temperatureinfo_windinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceHumidityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('reportTime', models.DateTimeField()),
                ('humidity', models.IntegerField()),
                ('humidity_float', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceTemperatureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('reportTime', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('temperature_float', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceWeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('reportTime', models.DateTimeField()),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceWindInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('reportTime', models.DateTimeField()),
                ('winddirection', models.CharField(max_length=50)),
                ('windpower', models.CharField(max_length=10)),
            ],
        ),
    ]
