# Generated by Django 5.0.7 on 2024-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_provincehumidityinfo_provincetemperatureinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPredictInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('reportTime', models.DateTimeField()),
                ('weather', models.CharField(max_length=50)),
                ('temperature_float', models.FloatField()),
                ('humidity_float', models.FloatField()),
                ('winddirection', models.CharField(max_length=50)),
                ('windpower', models.CharField(max_length=10)),
            ],
        ),
    ]
