apiVersion: batch/v1
kind: CronJob
metadata:
  name: predict-cronjob
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1 
  schedule: "*/30 * * * *"   # 每半小时执行一次
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: predict-container
            image: xrkkkt/docker_demo2:predict
            env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "23Liang02291515!"
            - name: DB_NAME
              value: "weather"
            imagePullPolicy: Always
          restartPolicy: OnFailure
