def translate_province(province_name):
    translation_dict = {
        '北京': 'Beijing',
        '天津': 'Tianjin',
        '河北': 'Hebei',
        '山西': 'Shanxi',
        '内蒙古': 'Inner Mongolia',
        '辽宁': 'Liaoning',
        '吉林': 'Jilin',
        '黑龙江': 'Heilongjiang',
        '上海': 'Shanghai',
        '江苏': 'Jiangsu',
        '浙江': 'Zhejiang',
        '安徽': 'Anhui',
        '福建': 'Fujian',
        '江西': 'Jiangxi',
        '山东': 'Shandong',
        '河南': 'Henan',
        '湖北': 'Hubei',
        '湖南': 'Hunan',
        '广东': 'Guangdong',
        '广西': 'Guangxi',
        '海南': 'Hainan',
        '重庆': 'Chongqing',
        '四川': 'Sichuan',
        '贵州': 'Guizhou',
        '云南': 'Yunnan',
        '西藏': 'Tibet',
        '陕西': 'Shaanxi',
        '甘肃': 'Gansu',
        '青海': 'Qinghai',
        '宁夏': 'Ningxia',
        '新疆': 'Xinjiang',
        '香港': 'Hong Kong',
        '澳门': 'Macau',
        '台湾': 'Taiwan'
    }

    return translation_dict.get(province_name, "Unknown Province")


def translate_weather(weather_description):
    translation_dict = {
        '晴': 'Clear',
        '少云': 'Partly Cloudy',
        '晴间多云': 'Sunny with Clouds',
        '多云': 'Cloudy',
        '阴': 'Overcast',
        '有风': 'Windy',
        '平静': 'Calm',
        '微风': 'Light Breeze',
        '和风': 'Gentle Breeze',
        '清风': 'Moderate Breeze',
        '强风/劲风': 'Fresh Breeze',
        '疾风': 'Strong Breeze',
        '大风': 'High Wind',
        '烈风': 'Gale',
        '风暴': 'Strong Gale',
        '狂爆风': 'Storm',
        '飓风': 'Violent Storm',
        '热带风暴': 'Tropical Storm',
        '霾': 'Haze',
        '中度霾': 'Moderate Haze',
        '重度霾': 'Heavy Haze',
        '严重霾': 'Severe Haze',
        '阵雨': 'Shower Rain',
        '雷阵雨': 'Thundershower',
        '雷阵雨并伴有冰雹': 'Thundershower with Hail',
        '小雨': 'Light Rain',
        '中雨': 'Moderate Rain',
        '大雨': 'Heavy Rain',
        '暴雨': 'Storm',
        '大暴雨': 'Heavy Storm',
        '特大暴雨': 'Severe Storm',
        '强阵雨': 'Strong Shower Rain',
        '强雷阵雨': 'Strong Thundershower',
        '极端降雨': 'Extreme Rainfall',
        '毛毛雨/细雨': 'Drizzle',
        '雨': 'Rain',
        '小雨-中雨': 'Light to Moderate Rain',
        '中雨-大雨': 'Moderate to Heavy Rain',
        '大雨-暴雨': 'Heavy Rain to Storm',
        '暴雨-大暴雨': 'Storm to Heavy Storm',
        '大暴雨-特大暴雨': 'Heavy to Severe Storm',
        '雨雪天气': 'Rain and Snow',
        '雨夹雪': 'Sleet',
        '阵雨夹雪': 'Shower with Snow',
        '冻雨': 'Freezing Rain',
        '雪': 'Snow',
        '阵雪': 'Snow Flurry',
        '小雪': 'Light Snow',
        '中雪': 'Moderate Snow',
        '大雪': 'Heavy Snow',
        '暴雪': 'Blizzard',
        '小雪-中雪': 'Light to Moderate Snow',
        '中雪-大雪': 'Moderate to Heavy Snow',
        '大雪-暴雪': 'Heavy Snow to Blizzard',
        '浮尘': 'Floating Dust',
        '扬沙': 'Blowing Sand',
        '沙尘暴': 'Sandstorm',
        '强沙尘暴': 'Severe Sandstorm',
        '龙卷风': 'Tornado',
        '雾': 'Fog',
        '浓雾': 'Dense Fog',
        '强浓雾': 'Strong Dense Fog',
        '轻雾': 'Light Fog',
        '大雾': 'Heavy Fog',
        '特强浓雾': 'Extra Heavy Fog',
        '热': 'Hot',
        '冷': 'Cold',
        '未知': 'Unknown'
    }

    return translation_dict.get(weather_description, "Unknown Weather")


def translate_wind_direction(wind_direction):
    translations = {
        "无风向": "Calm",
        "东北": "Northeast",
        "东": "East",
        "东南": "Southeast",
        "南": "South",
        "西南": "Southwest",
        "西": "West",
        "西北": "Northwest",
        "北": "North",
        "旋转不定": "Variable"
    }
    return translations.get(wind_direction, "Unknown")