apiVersion: v1
kind: Service
metadata:
  name: bw-svc
spec:
  selector:
    app: backend-weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
  type: NodePort
