FROM node:14 as build
COPY ./ /app
WORKDIR /app
RUN npm install && npm run build

FROM nginx
RUN mkdir /app
COPY --from=build /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM node:14 as build
# COPY ./ /app
# WORKDIR /app
# RUN npm install && npm run dev
